package servlet;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import thealeke.Thealekeweb;
import thealeke.Thealekeweb_Service;
import thealeke.Transaction;

public class transactionClient extends HttpServlet {

    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        if (request.getSession(false).getAttribute("username") == null && request.getSession(false).getAttribute("password") == null) {

            response.sendRedirect("index.jsp");
        }
        response.setContentType("text/html;charset=UTF-8");
        String output = "";
        HttpSession session = request.getSession();
        //String role=session.getAttribute("role");

        if (session.getAttribute("username") == null || session.getAttribute("password") == null) {
            // response.sendRedirect("LOGIN.jsp");

            Thealekeweb_Service service = new Thealekeweb_Service();//connecting to the RPCwebservice to calllogin methode
            Thealekeweb proxy = service.getThealekewebPort();//connecting to the RPCwebservice to calllogin methode
            //        ArrayList<rpc.>
            /* TODO output your page here. You may use following sample code. */
            response.setContentType("text/html;charset=UTF-8");
            try (PrintWriter out = response.getWriter()) {

//session.getAttribute("username") != null && session.getAttribute("password") != null
                if (true) {

                    output = "<!DOCTYPE html>\n"
                            + "<html lang=\"en\">\n"
                            + "    <head>\n"
                            + "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n"
                            + "        <meta charset=\"utf-8\" />\n"
                            + "        <title>BANK OF ETHIOPIA</title>\n"
                            + "\n"
                            + "        <meta name=\"description\" content=\"Static &amp; Dynamic Tables\" />\n"
                            + "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\" />\n"
                            + "\n"
                            + "        <!-- bootstrap & fontawesome -->\n"
                            + "        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\" />\n"
                            + "        <link rel=\"stylesheet\" href=\"assets/font-awesome/4.5.0/css/font-awesome.min.css\" />\n"
                            + "\n"
                            + "        <!-- page specific plugin styles -->\n"
                            + "\n"
                            + "        <!-- text fonts -->\n"
                            + "        <link rel=\"stylesheet\" href=\"assets/css/fonts.googleapis.com.css\" />\n"
                            + "\n"
                            + "        <!-- ace styles -->\n"
                            + "        <link rel=\"stylesheet\" href=\"assets/css/ace.min.css\" class=\"ace-main-stylesheet\" id=\"main-ace-style\" />\n"
                            + "\n"
                            + "        <!--[if lte IE 9]>\n"
                            + "                <link rel=\"stylesheet\" href=\"assets/css/ace-part2.min.css\" class=\"ace-main-stylesheet\" />\n"
                            + "        <![endif]-->\n"
                            + "        <link rel=\"stylesheet\" href=\"assets/css/ace-skins.min.css\" />\n"
                            + "        <link rel=\"stylesheet\" href=\"assets/css/ace-rtl.min.css\" />\n"
                            + "\n"
                            + "        <!--[if lte IE 9]>\n"
                            + "          <link rel=\"stylesheet\" href=\"assets/css/ace-ie.min.css\" />\n"
                            + "        <![endif]-->\n"
                            + "\n"
                            + "        <!-- inline styles related to this page -->\n"
                            + "\n"
                            + "        <!-- ace settings handler -->\n"
                            + "        <script src=\"assets/js/ace-extra.min.js\"></script>\n"
                            + "\n"
                            + "        <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->\n"
                            + "\n"
                            + "        <!--[if lte IE 8]>\n"
                            + "        <script src=\"assets/js/html5shiv.min.js\"></script>\n"
                            + "        <script src=\"assets/js/respond.min.js\"></script>\n"
                            + "        <![endif]-->\n"
                            + "    </head>\n"
                            + "\n"
                            + "    <body class=\"no-skin\">\n"
                            + "        <div id=\"navbar\" class=\"navbar navbar-default          ace-save-state\">\n"
                            + "            <div class=\"navbar-container ace-save-state\" id=\"navbar-container\">\n"
                            + "                <button type=\"button\" class=\"navbar-toggle menu-toggler pull-left\" id=\"menu-toggler\" data-target=\"#sidebar\">\n"
                            + "                    <span class=\"sr-only\">Toggle sidebar</span>\n"
                            + "\n"
                            + "                    <span class=\"icon-bar\"></span>\n"
                            + "\n"
                            + "                    <span class=\"icon-bar\"></span>\n"
                            + "\n"
                            + "                    <span class=\"icon-bar\"></span>\n"
                            + "                </button>\n"
                            + "\n"
                            + "                <div class=\"navbar-header pull-left\">\n"
                            + "                    <a href=\"index.html\" class=\"navbar-brand\">\n"
                            + "                        <small>\n"
                            + "                            <i class=\"fa fa-leaf\"></i>\n"
                            + "                            BANK OF ETHIOPIA\n"
                            + "                        </small>\n"
                            + "                    </a>\n"
                            + "                </div>\n"
                            + "\n"
                            + "                <div class=\"navbar-buttons navbar-header pull-right\" role=\"navigation\">\n"
                            + "                    <ul class=\"nav ace-nav\">\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                        <li class=\"light-blue dropdown-modal\">\n"
                            + "                            <a data-toggle=\"dropdown\" href=\"#\" class=\"dropdown-toggle\">\n"
                            + "                                <img class=\"nav-user-photo\" src=\"assets/images/avatars/user.jpg\" alt=\"Jason's Photo\" />\n"
                            + "                                <span class=\"user-info\">\n"
                            + "                                    <small>Welcome,</small>\n"
                            + "                                    Jason\n"
                            + "                                </span>\n"
                            + "\n"
                            + "                                <i class=\"ace-icon fa fa-caret-down\"></i>\n"
                            + "                            </a>\n"
                            + "\n"
                            + "                            <ul class=\"user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close\">\n"
                            + "                                <li>\n"
                            + "                                    <a href=\"#\">\n"
                            + "                                        <i class=\"ace-icon fa fa-cog\"></i>\n"
                            + "                                        Settings\n"
                            + "                                    </a>\n"
                            + "                                </li>\n"
                            + "\n"
                            + "                                <li>\n"
                            + "                                    <a href=\"profile.html\">\n"
                            + "                                        <i class=\"ace-icon fa fa-user\"></i>\n"
                            + "                                        Profile\n"
                            + "                                    </a>\n"
                            + "                                </li>\n"
                            + "\n"
                            + "                                <li class=\"divider\"></li>\n"
                            + "\n"
                            + "                                <li>\n"
                            + "                                    <a href=\"#\">\n"
                            + "                                        <i class=\"ace-icon fa fa-power-off\"></i>\n"
                            + "                                        Logout\n"
                            + "                                    </a>\n"
                            + "                                </li>\n"
                            + "                            </ul>\n"
                            + "                        </li>\n"
                            + "                    </ul>\n"
                            + "                </div>\n"
                            + "            </div><!-- /.navbar-container -->\n"
                            + "        </div>\n"
                            + "\n"
                            + "        <div class=\"main-container ace-save-state\" id=\"main-container\">\n"
                            + "            <script type=\"text/javascript\">\n"
                            + "                try {\n"
                            + "                    ace.settings.loadState('main-container')\n"
                            + "                } catch (e) {\n"
                            + "                }\n"
                            + "            </script>\n"
                            + "\n"
                            + "            <div id=\"sidebar\" class=\"sidebar                  responsive                    ace-save-state\">\n"
                            + "                <script type=\"text/javascript\">\n"
                            + "                    try {\n"
                            + "                        ace.settings.loadState('sidebar')\n"
                            + "                    } catch (e) {\n"
                            + "                    }\n"
                            + "                </script>\n"
                            + "\n"
                            + "                <div class=\"sidebar-shortcuts\" id=\"sidebar-shortcuts\">\n"
                            + "                    <div class=\"sidebar-shortcuts-large\" id=\"sidebar-shortcuts-large\">\n"
                            + "                        <button class=\"btn btn-success\">\n"
                            + "                            <i class=\"ace-icon fa fa-signal\"></i>\n"
                            + "                        </button>\n"
                            + "\n"
                            + "                        <button class=\"btn btn-info\">\n"
                            + "                            <i class=\"ace-icon fa fa-pencil\"></i>\n"
                            + "                        </button>\n"
                            + "\n"
                            + "                        <button class=\"btn btn-warning\">\n"
                            + "                            <i class=\"ace-icon fa fa-users\"></i>\n"
                            + "                        </button>\n"
                            + "\n"
                            + "                        <button class=\"btn btn-danger\">\n"
                            + "                            <i class=\"ace-icon fa fa-cogs\"></i>\n"
                            + "                        </button>\n"
                            + "                    </div>\n"
                            + "\n"
                            + "                    <div class=\"sidebar-shortcuts-mini\" id=\"sidebar-shortcuts-mini\">\n"
                            + "                        <span class=\"btn btn-success\"></span>\n"
                            + "\n"
                            + "                        <span class=\"btn btn-info\"></span>\n"
                            + "\n"
                            + "                        <span class=\"btn btn-warning\"></span>\n"
                            + "\n"
                            + "                        <span class=\"btn btn-danger\"></span>\n"
                            + "                    </div>\n"
                            + "                </div><!-- /.sidebar-shortcuts -->\n"
                            + "\n"
                            + "                <ul class=\"nav nav-list\">\n"
                            + "                    <li class=\"\">\n"
                            + "                        <a href=\"index.html\">\n"
                            + "                            <i class=\"menu-icon fa fa-tachometer\"></i>\n"
                            + "                            <span class=\"menu-text\"> Dashboard </span>\n"
                            + "                        </a>\n"
                            + "\n"
                            + "                        <b class=\"arrow\"></b>\n"
                            + "                    </li>\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                    <li class=\"\">\n"
                            + "                        <a href=\"#\" class=\"dropdown-toggle\">\n"
                            + "                            <i class=\"menu-icon fa fa-list\"></i>\n"
                            + "                            <span class=\"menu-text\"> DEPOSITE </span>\n"
                            + "\n"
                            + "\n"
                            + "                        </a>\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                    </li>\n"
                            + "\n"
                            + "                    <li class=\"\">\n"
                            + "                        <a href=\"#\" class=\"dropdown-toggle\">\n"
                            + "                            <i class=\"menu-icon fa fa-pencil-square-o\"></i>\n"
                            + "                            <span class=\"menu-text\"> WITHDRAW </span>\n"
                            + "\n"
                            + "\n"
                            + "                        </a>\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                    </li>\n"
                            + "\n"
                            + "                    <li class=\"\">\n"
                            + "                        <a href=\"widgets.html\">\n"
                            + "                            <i class=\"menu-icon fa fa-list-alt\"></i>\n"
                            + "                            <span class=\"menu-text\"> TRANSFER </span>\n"
                            + "                        </a>\n"
                            + "\n"
                            + "                        <b class=\"arrow\"></b>\n"
                            + "                    </li>\n"
                            + "\n"
                            + "                    <li class=\"\">\n"
                            + "                        <a href=\"calendar.html\">\n"
                            + "                            <i class=\"menu-icon fa fa-calendar\"></i>\n"
                            + "\n"
                            + "                            <span class=\"menu-text\">\n"
                            + "                                TRANSACTION\n"
                            + "\n"
                            + "\n"
                            + "                            </span>\n"
                            + "                        </a>\n"
                            + "\n"
                            + "                        <b class=\"arrow\"></b>\n"
                            + "                    </li>\n"
                            + "\n"
                            + "                    <li class=\"\">\n"
                            + "                        <a href=\"gallery.html\">\n"
                            + "                            <i class=\"menu-icon fa fa-picture-o\"></i>\n"
                            + "                            <span class=\"menu-text\"> CREATE ACOUNT </span>\n"
                            + "                        </a>\n"
                            + "\n"
                            + "                        <b class=\"arrow\"></b>\n"
                            + "                    </li>\n"
                            + "\n"
                            + "                    <li class=\"\">\n"
                            + "                        <a href=\"#\" class=\"dropdown-toggle\">\n"
                            + "                            <i class=\"menu-icon fa fa-tag\"></i>\n"
                            + "                            <span class=\"menu-text\"> MANAGE ACCOUNT </span>\n"
                            + "\n"
                            + "\n"
                            + "                        </a>\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                    </li>\n"
                            + "\n"
                            + "                    <li class=\"active open\">\n"
                            + "                        <a href=\"#\" class=\"dropdown-toggle\">\n"
                            + "                            <i class=\"menu-icon fa fa-file-o\"></i>\n"
                            + "\n"
                            + "                            <span class=\"menu-text\">\n"
                            + "                                Other Pages\n"
                            + "\n"
                            + "                            </span>\n"
                            + "\n"
                            + "\n"
                            + "                        </a>\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                    </li>\n"
                            + "                </ul><!-- /.nav-list -->\n"
                            + "\n"
                            + "                <div class=\"sidebar-toggle sidebar-collapse\" id=\"sidebar-collapse\">\n"
                            + "                    <i id=\"sidebar-toggle-icon\" class=\"ace-icon fa fa-angle-double-left ace-save-state\" data-icon1=\"ace-icon fa fa-angle-double-left\" data-icon2=\"ace-icon fa fa-angle-double-right\"></i>\n"
                            + "                </div>\n"
                            + "            </div>\n"
                            + "\n"
                            + "            <div class=\"main-content\">\n"
                            + "                <div class=\"main-content-inner\">\n"
                            + "                    <div class=\"breadcrumbs ace-save-state\" id=\"breadcrumbs\">\n"
                            + "                        <ul class=\"breadcrumb\">\n"
                            + "                            <li>\n"
                            + "                                <i class=\"ace-icon fa fa-home home-icon\"></i>\n"
                            + "                                <a href=\"#\">Home</a>\n"
                            + "                            </li>\n"
                            + "\n"
                            + "                            <li>\n"
                            + "                                <a href=\"#\">TRANSACTION</a>\n"
                            + "                            </li>\n"
                            + "\n"
                            + "                        </ul><!-- /.breadcrumb -->\n"
                            + "\n"
                            + "\n"
                            + "                    </div>\n"
                            + "\n"
                            + "                    <div class=\"page-content\">\n"
                            + "                        <div class=\"ace-settings-container\" id=\"ace-settings-container\">\n"
                            + "                            <div class=\"btn btn-app btn-xs btn-warning ace-settings-btn\" id=\"ace-settings-btn\">\n"
                            + "                                <i class=\"ace-icon fa fa-cog bigger-130\"></i>\n"
                            + "                            </div>\n"
                            + "\n"
                            + "                            <div class=\"ace-settings-box clearfix\" id=\"ace-settings-box\">\n"
                            + "                                <div class=\"pull-left width-50\">\n"
                            + "                                    <div class=\"ace-settings-item\">\n"
                            + "                                        <div class=\"pull-left\">\n"
                            + "                                            <select id=\"skin-colorpicker\" class=\"hide\">\n"
                            + "                                                <option data-skin=\"no-skin\" value=\"#438EB9\">#438EB9</option>\n"
                            + "                                                <option data-skin=\"skin-1\" value=\"#222A2D\">#222A2D</option>\n"
                            + "                                                <option data-skin=\"skin-2\" value=\"#C6487E\">#C6487E</option>\n"
                            + "                                                <option data-skin=\"skin-3\" value=\"#D0D0D0\">#D0D0D0</option>\n"
                            + "                                            </select>\n"
                            + "                                        </div>\n"
                            + "                                        <span>&nbsp; Choose Skin</span>\n"
                            + "                                    </div>\n"
                            + "\n"
                            + "                                    <div class=\"ace-settings-item\">\n"
                            + "                                        <input type=\"checkbox\" class=\"ace ace-checkbox-2 ace-save-state\" id=\"ace-settings-navbar\" autocomplete=\"off\" />\n"
                            + "                                        <label class=\"lbl\" for=\"ace-settings-navbar\"> Fixed Navbar</label>\n"
                            + "                                    </div>\n"
                            + "\n"
                            + "                                    <div class=\"ace-settings-item\">\n"
                            + "                                        <input type=\"checkbox\" class=\"ace ace-checkbox-2 ace-save-state\" id=\"ace-settings-sidebar\" autocomplete=\"off\" />\n"
                            + "                                        <label class=\"lbl\" for=\"ace-settings-sidebar\"> Fixed Sidebar</label>\n"
                            + "                                    </div>\n"
                            + "\n"
                            + "                                    <div class=\"ace-settings-item\">\n"
                            + "                                        <input type=\"checkbox\" class=\"ace ace-checkbox-2 ace-save-state\" id=\"ace-settings-breadcrumbs\" autocomplete=\"off\" />\n"
                            + "                                        <label class=\"lbl\" for=\"ace-settings-breadcrumbs\"> Fixed Breadcrumbs</label>\n"
                            + "                                    </div>\n"
                            + "\n"
                            + "                                    <div class=\"ace-settings-item\">\n"
                            + "                                        <input type=\"checkbox\" class=\"ace ace-checkbox-2\" id=\"ace-settings-rtl\" autocomplete=\"off\" />\n"
                            + "                                        <label class=\"lbl\" for=\"ace-settings-rtl\"> Right To Left (rtl)</label>\n"
                            + "                                    </div>\n"
                            + "\n"
                            + "                                    <div class=\"ace-settings-item\">\n"
                            + "                                        <input type=\"checkbox\" class=\"ace ace-checkbox-2 ace-save-state\" id=\"ace-settings-add-container\" autocomplete=\"off\" />\n"
                            + "                                        <label class=\"lbl\" for=\"ace-settings-add-container\">\n"
                            + "                                            Inside\n"
                            + "                                            <b>.container</b>\n"
                            + "                                        </label>\n"
                            + "                                    </div>\n"
                            + "                                </div><!-- /.pull-left -->\n"
                            + "\n"
                            + "                                <div class=\"pull-left width-50\">\n"
                            + "                                    <div class=\"ace-settings-item\">\n"
                            + "                                        <input type=\"checkbox\" class=\"ace ace-checkbox-2\" id=\"ace-settings-hover\" autocomplete=\"off\" />\n"
                            + "                                        <a href=\"TRANSACTION_CLIENT.jsp\"></a>\n"
                            + "                                        <label class=\"lbl\" for=\"ace-settings-hover\"> Submenu on Hover</label>\n"
                            + "                                    </div>\n"
                            + "\n"
                            + "                                    <div class=\"ace-settings-item\">\n"
                            + "                                        <input type=\"checkbox\" class=\"ace ace-checkbox-2\" id=\"ace-settings-compact\" autocomplete=\"off\" />\n"
                            + "                                        <label class=\"lbl\" for=\"ace-settings-compact\"> Compact Sidebar</label>\n"
                            + "                                    </div>\n"
                            + "\n"
                            + "                                    <div class=\"ace-settings-item\">\n"
                            + "                                        <input type=\"checkbox\" class=\"ace ace-checkbox-2\" id=\"ace-settings-highlight\" autocomplete=\"off\" />\n"
                            + "                                        <label class=\"lbl\" for=\"ace-settings-highlight\"> Alt. Active Item</label>\n"
                            + "                                    </div>\n"
                            + "                                </div><!-- /.pull-left -->\n"
                            + "                            </div><!-- /.ace-settings-box -->\n"
                            + "                        </div><!-- /.ace-settings-container -->\n"
                            + "\n"
                            + "\n"
                            + "                        \n"
                            + "                        <div class=\"row\">\n"
                            + "                            <div class=\"col-xs-12\">\n"
                            + "                                <!-- PAGE CONTENT BEGINS -->\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                                <div class=\"row\">\n"
                            + "                                    <div class=\"col-xs-12\">\n"
                            + "\n"
                            + "                                        <div class=\"clearfix\">\n"
                            + "                                            <div class=\"pull-right tableTools-container\"></div>\n"
                            + "                                        </div>\n"
                            + "                                        <div class=\"table-header\">\n"
                            + "                                            RECENT TRANSACTION REPORT\n"
                            + "                                        </div>\n"
                            + "\n"
                            + "                                        <!-- div.table-responsive -->\n"
                            + "\n"
                            + "                                        <!-- div.dataTables_borderWrap -->\n"
                            + "                                        <div>\n"
                            + "                                            <table id=\"dynamic-table\" class=\"table table-striped table-bordered table-hover\">\n"
                            + "                                                <thead>\n"
                            + "                                                    <tr>\n"
                            + "                                                        <th class=\"center\">\n"
                            + "                                                            <label class=\"pos-rel\">\n"
                            + "                                                                <input type=\"checkbox\" class=\"ace\" />\n"
                            + "                                                                <span class=\"lbl\"></span>\n"
                            + "                                                            </label>\n"
                            + "                                                        </th>\n"
                            + "                                                        <th>Domain</th>\n"
                            + "                                                        <th>Price</th>\n"
                            + "                                                        <th class=\"hidden-480\">Clicks</th>\n"
                            + "\n"
                            + "                                                        <th>\n"
                            + "                                                            <i class=\"ace-icon fa fa-clock-o bigger-110 hidden-480\"></i>\n"
                            + "                                                            Update\n"
                            + "                                                        </th>\n"
                            + "                                                        <th class=\"hidden-480\">Status</th>\n"
                            + "\n"
                            + "                                                        <th></th>\n"
                            + "                                                    </tr>\n"
                            + "                                                </thead>\n";

                    output = output + "<tr>\\n\" +\n"
                            + "\"                                                        <td class=\\\"center\\\">\\n\" +\n"
                            + "\"                                                            <label class=\\\"pos-rel\\\">\\n\" +\n"
                            + "\"                                                                <input type=\\\"checkbox\\\" class=\\\"ace\\\" />\\n\" +\n"
                            + "\"                                                                <span class=\\\"lbl\\\"></span>\\n\" +\n"
                            + "\"                                                            </label>\\n\" +\n"
                            + "\"                                                        </td>\\n\" +\n"
                            + "\"\\n\" +\n"
                            + "\"                                                        <td>\\n\" +\n"
                            + "\"                                                            <a href=\\\"#\\\">app.com</a>\\n\" +\n"
                            + "\"                                                        </td>\\n\" +\n"
                            + "\"                                                        <td>$45</td>\\n\" +\n"
                            + "\"                                                        <td class=\\\"hidden-480\\\">3,330</td>\\n\" +\n"
                            + "\"                                                        <td>Feb 12</td>\\n\" +\n"
                            + "\"\\n\" +\n"
                            + "\"                                                        <td class=\\\"hidden-480\\\">\\n\" +\n"
                            + "\"                                                            <span class=\\\"label label-sm label-warning\\\">Expiring</span>\\n\" +\n"
                            + "\"                                                        </td>\\n\" +\n"
                            + "\"\\n\" +\n"
                            + "\"                                                        <td>\\n\" +\n"
                            + "\"                                                            <div class=\\\"hidden-sm hidden-xs action-buttons\\\">\\n\" +\n"
                            + "\"                                                                <a class=\\\"blue\\\" href=\\\"#\\\">\\n\" +\n"
                            + "\"                                                                    <i class=\\\"ace-icon fa fa-search-plus bigger-130\\\"></i>\\n\" +\n"
                            + "\"                                                                </a>\\n\" +\n"
                            + "\"\\n\" +\n"
                            + "\"                                                                <a class=\\\"green\\\" href=\\\"#\\\">\\n\" +\n"
                            + "\"                                                                    <i class=\\\"ace-icon fa fa-pencil bigger-130\\\"></i>\\n\" +\n"
                            + "\"                                                                </a>\\n\" +\n"
                            + "\"\\n\" +\n"
                            + "\"                                                                <a class=\\\"red\\\" href=\\\"#\\\">\\n\" +\n"
                            + "\"                                                                    <i class=\\\"ace-icon fa fa-trash-o bigger-130\\\"></i>\\n\" +\n"
                            + "\"                                                                </a>\\n\" +\n"
                            + "\"                                                            </div>\\n\" +\n"
                            + "\"\\n\" +\n"
                            + "\"                                                            <div class=\\\"hidden-md hidden-lg\\\">\\n\" +\n"
                            + "\"                                                                <div class=\\\"inline pos-rel\\\">\\n\" +\n"
                            + "\"                                                                    <button class=\\\"btn btn-minier btn-yellow dropdown-toggle\\\" data-toggle=\\\"dropdown\\\" data-position=\\\"auto\\\">\\n\" +\n"
                            + "\"                                                                        <i class=\\\"ace-icon fa fa-caret-down icon-only bigger-120\\\"></i>\\n\" +\n"
                            + "\"                                                                    </button>\\n\" +\n"
                            + "\"\\n\" +\n"
                            + "\"                                                                    <ul class=\\\"dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close\\\">\\n\" +\n"
                            + "\"                                                                        <li>\\n\" +\n"
                            + "\"                                                                            <a href=\\\"#\\\" class=\\\"tooltip-info\\\" data-rel=\\\"tooltip\\\" title=\\\"View\\\">\\n\" +\n"
                            + "\"                                                                                <span class=\\\"blue\\\">\\n\" +\n"
                            + "\"                                                                                    <i class=\\\"ace-icon fa fa-search-plus bigger-120\\\"></i>\\n\" +\n"
                            + "\"                                                                                </span>\\n\" +\n"
                            + "\"                                                                            </a>\\n\" +\n"
                            + "\"                                                                        </li>\\n\" +\n"
                            + "\"\\n\" +\n"
                            + "\"                                                                        <li>\\n\" +\n"
                            + "\"                                                                            <a href=\\\"#\\\" class=\\\"tooltip-success\\\" data-rel=\\\"tooltip\\\" title=\\\"Edit\\\">\\n\" +\n"
                            + "\"                                                                                <span class=\\\"green\\\">\\n\" +\n"
                            + "\"                                                                                    <i class=\\\"ace-icon fa fa-pencil-square-o bigger-120\\\"></i>\\n\" +\n"
                            + "\"                                                                                </span>\\n\" +\n"
                            + "\"                                                                            </a>\\n\" +\n"
                            + "\"                                                                        </li>\\n\" +\n"
                            + "\"\\n\" +\n"
                            + "\"                                                                        <li>\\n\" +\n"
                            + "\"                                                                            <a href=\\\"#\\\" class=\\\"tooltip-error\\\" data-rel=\\\"tooltip\\\" title=\\\"Delete\\\">\\n\" +\n"
                            + "\"                                                                                <span class=\\\"red\\\">\\n\" +\n"
                            + "\"                                                                                    <i class=\\\"ace-icon fa fa-trash-o bigger-120\\\"></i>\\n\" +\n"
                            + "\"                                                                                </span>\\n\" +\n"
                            + "\"                                                                            </a>\\n\" +\n"
                            + "\"                                                                        </li>\\n\" +\n"
                            + "\"                                                                    </ul>\\n\" +\n"
                            + "\"                                                                </div>\\n\" +\n"
                            + "\"                                                            </div>\\n\" +\n"
                            + "\"                                                        </td>\\n\" +\n"
                            + "\"                                                    </tr>\\n\" +";
                    ArrayList<Transaction> array1 = (ArrayList<Transaction>) proxy.transaction1("client", 3, 10000);
                    Transaction tran = array1.get(0);
                    output = output + "<tbody>\n </tbody>\n"
                            + "                                            </table>\n"
                            + "                                        </div>\n"
                            + "                                    </div>\n"
                            + "                                </div>\n"
                            + "\n"
                            + "                                <div id=\"modal-table\" class=\"modal fade\" tabindex=\"-1\">\n"
                            + "                                    <div class=\"modal-dialog\">\n"
                            + "                                        <div class=\"modal-content\">\n"
                            + "                                            <div class=\"modal-header no-padding\">\n"
                            + "                                                <div class=\"table-header\">\n"
                            + "                                                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">\n"
                            + "                                                        <span class=\"white\">&times;</span>\n"
                            + "                                                    </button>\n"
                            + "                                                    Results for \"Latest Registered Domains\n"
                            + "                                                </div>\n"
                            + "                                            </div>\n"
                            + "\n"
                            + "                                            <div class=\"modal-body no-padding\">\n"
                            + "                                                <table class=\"table table-striped table-bordered table-hover no-margin-bottom no-border-top\">\n"
                            + "                                                    <thead>\n"
                            + "                                                        <tr>\n"
                            + "                                                            <th>done by</th>\n"
                            + "                                                            <th>transaction</th>\n"
                            + "                                                            <th>ammount</th>\n"
                            + "                                                            <th>Account number</th>\n"
                            + "                                                            <th>account holder</th>\n"
                            + "\n"
                            + "                                                            <th>\n"
                            + "                                                                <i class=\"ace-icon fa fa-clock-o bigger-110\"></i>\n"
                            + "                                                                date\n"
                            + "                                                            </th>\n"
                            + "                                                        </tr>\n"
                            + "                                                    </thead>\n"
                            + "\n"
                            + "                                                    <tbody>\n"
                            + "                                                        <tr>\n"
                            + "                                                            <td>\n"
                            + "                                                                <a href=\"#\">" + tran.getExecutedby() + "</a>\n"
                            + "                                                            </td>\n"
                            + "                                                            <td>" + tran.getType() + "</td>\n"
                            + "                                                            <td>" + tran.getAmount() + "</td>\n"
                            + "                                                            <td>" + tran.getDate() + "</td>\n"
                            + "                                                            <td>" + tran.getAccnum() + "</td>\n"
                            + "                                                            <td>" + tran.getName() + "</td>\n"
                            + "                                                        </tr>\n"
                            + "\n"
                            + "                                                        <tr>\n"
                            + "                                                            <td>\n"
                            + "                                                                <a href=\"#\">base.com</a>\n"
                            + "                                                            </td>\n"
                            + "                                                            <td>$35</td>\n"
                            + "                                                            <td>2,595</td>\n"
                            + "                                                            <td>Feb 18</td>\n"
                            + "                                                        </tr>\n"
                            + "\n"
                            + "                                                        <tr>\n"
                            + "                                                            <td>\n"
                            + "                                                                <a href=\"#\">max.com</a>\n"
                            + "                                                            </td>\n"
                            + "                                                            <td>$60</td>\n"
                            + "                                                            <td>4,400</td>\n"
                            + "                                                            <td>Mar 11</td>\n"
                            + "                                                        </tr>\n"
                            + "\n"
                            + "                                                        <tr>\n"
                            + "                                                            <td>\n"
                            + "                                                                <a href=\"#\">best.com</a>\n"
                            + "                                                            </td>\n"
                            + "                                                            <td>$75</td>\n"
                            + "                                                            <td>6,500</td>\n"
                            + "                                                            <td>Apr 03</td>\n"
                            + "                                                        </tr>\n"
                            + "\n"
                            + "                                                        <tr>\n"
                            + "                                                            <td>\n"
                            + "                                                                <a href=\"#\">pro.com</a>\n"
                            + "                                                            </td>\n"
                            + "                                                            <td>$55</td>\n"
                            + "                                                            <td>4,250</td>\n"
                            + "                                                            <td>Jan 21</td>\n"
                            + "                                                        </tr>\n"
                            + "                                                    </tbody>\n"
                            + "                                                </table>\n"
                            + "                                            </div>\n"
                            + "\n"
                            + "                                            <div class=\"modal-footer no-margin-top\">\n"
                            + "                                                <button class=\"btn btn-sm btn-danger pull-left\" data-dismiss=\"modal\">\n"
                            + "                                                    <i class=\"ace-icon fa fa-times\"></i>\n"
                            + "                                                    Close\n"
                            + "                                                </button>\n"
                            + "\n"
                            + "                                                <ul class=\"pagination pull-right no-margin\">\n"
                            + "                                                    <li class=\"prev disabled\">\n"
                            + "                                                        <a href=\"#\">\n"
                            + "                                                            <i class=\"ace-icon fa fa-angle-double-left\"></i>\n"
                            + "                                                        </a>\n"
                            + "                                                    </li>\n"
                            + "\n"
                            + "                                                    <li class=\"active\">\n"
                            + "                                                        <a href=\"#\">1</a>\n"
                            + "                                                    </li>\n"
                            + "\n"
                            + "                                                    <li>\n"
                            + "                                                        <a href=\"#\">2</a>\n"
                            + "                                                    </li>\n"
                            + "\n"
                            + "                                                    <li>\n"
                            + "                                                        <a href=\"#\">3</a>\n"
                            + "                                                    </li>\n"
                            + "\n"
                            + "                                                    <li class=\"next\">\n"
                            + "                                                        <a href=\"#\">\n"
                            + "                                                            <i class=\"ace-icon fa fa-angle-double-right\"></i>\n"
                            + "                                                        </a>\n"
                            + "                                                    </li>\n"
                            + "                                                </ul>\n"
                            + "                                            </div>\n"
                            + "                                        </div><!-- /.modal-content -->\n"
                            + "                                    </div><!-- /.modal-dialog -->\n"
                            + "                                </div>\n"
                            + "\n"
                            + "                                <!-- PAGE CONTENT ENDS -->\n"
                            + "                            </div><!-- /.col -->\n"
                            + "                        </div><!-- /.row -->\n"
                            + "                    </div><!-- /.page-content -->\n"
                            + "                </div>\n"
                            + "            </div><!-- /.main-content -->\n"
                            + "\n"
                            + "            <div class=\"footer\">\n"
                            + "                <div class=\"footer-inner\">\n"
                            + "                    <div class=\"footer-content\">\n"
                            + "                        <span class=\"bigger-120\">\n"
                            + "                            <span class=\"blue bolder\">Ace</span>\n"
                            + "                            Application &copy; 2013-2014\n"
                            + "                        </span>\n"
                            + "\n"
                            + "                        &nbsp; &nbsp;\n"
                            + "                        <span class=\"action-buttons\">\n"
                            + "                            <a href=\"#\">\n"
                            + "                                <i class=\"ace-icon fa fa-twitter-square light-blue bigger-150\"></i>\n"
                            + "                            </a>\n"
                            + "\n"
                            + "                            <a href=\"#\">\n"
                            + "                                <i class=\"ace-icon fa fa-facebook-square text-primary bigger-150\"></i>\n"
                            + "                            </a>\n"
                            + "\n"
                            + "                            <a href=\"#\">\n"
                            + "                                <i class=\"ace-icon fa fa-rss-square orange bigger-150\"></i>\n"
                            + "                            </a>\n"
                            + "                        </span>\n"
                            + "                    </div>\n"
                            + "                </div>\n"
                            + "            </div>\n"
                            + "\n"
                            + "            <a href=\"#\" id=\"btn-scroll-up\" class=\"btn-scroll-up btn btn-sm btn-inverse\">\n"
                            + "                <i class=\"ace-icon fa fa-angle-double-up icon-only bigger-110\"></i>\n"
                            + "            </a>\n"
                            + "        </div><!-- /.main-container -->\n"
                            + "\n"
                            + "        <!-- basic scripts -->\n"
                            + "\n"
                            + "        <!--[if !IE]> -->\n"
                            + "        <script src=\"assets/js/jquery-2.1.4.min.js\"></script>\n"
                            + "\n"
                            + "        <!-- <![endif]-->\n"
                            + "\n"
                            + "        <!--[if IE]>\n"
                            + "<script src=\"assets/js/jquery-1.11.3.min.js\"></script>\n"
                            + "<![endif]-->\n"
                            + "        <script type=\"text/javascript\">\n"
                            + "                    if ('ontouchstart' in document.documentElement)\n"
                            + "                        document.write(\"<script src='assets/js/jquery.mobile.custom.min.js'>\" + \"<\" + \"/script>\");\n"
                            + "        </script>\n"
                            + "        <script src=\"assets/js/bootstrap.min.js\"></script>\n"
                            + "\n"
                            + "        <!-- page specific plugin scripts -->\n"
                            + "        <script src=\"assets/js/jquery.dataTables.min.js\"></script>\n"
                            + "        <script src=\"assets/js/jquery.dataTables.bootstrap.min.js\"></script>\n"
                            + "        <script src=\"assets/js/dataTables.buttons.min.js\"></script>\n"
                            + "        <script src=\"assets/js/buttons.flash.min.js\"></script>\n"
                            + "        <script src=\"assets/js/buttons.html5.min.js\"></script>\n"
                            + "        <script src=\"assets/js/buttons.print.min.js\"></script>\n"
                            + "        <script src=\"assets/js/buttons.colVis.min.js\"></script>\n"
                            + "        <script src=\"assets/js/dataTables.select.min.js\"></script>\n"
                            + "\n"
                            + "        <!-- ace scripts -->\n"
                            + "        <script src=\"assets/js/ace-elements.min.js\"></script>\n"
                            + "        <script src=\"assets/js/ace.min.js\"></script>\n"
                            + "\n"
                            + "        <!-- inline scripts related to this page -->\n"
                            + "        <script type=\"text/javascript\">\n"
                            + "                    jQuery(function ($) {\n"
                            + "                        //initiate dataTables plugin\n"
                            + "                        var myTable =\n"
                            + "                                $('#dynamic-table')\n"
                            + "                                //.wrap(\"<div class='dataTables_borderWrap' />\")   //if you are applying horizontal scrolling (sScrollX)\n"
                            + "                                .DataTable({\n"
                            + "                                    bAutoWidth: false,\n"
                            + "                                    \"aoColumns\": [\n"
                            + "                                        {\"bSortable\": false},\n"
                            + "                                        null, null, null, null, null,\n"
                            + "                                        {\"bSortable\": false}\n"
                            + "                                    ],\n"
                            + "                                    \"aaSorting\": [],\n"
                            + "                                    //\"bProcessing\": true,\n"
                            + "                                    //\"bServerSide\": true,\n"
                            + "                                    //\"sAjaxSource\": \"http://127.0.0.1/table.php\"	,\n"
                            + "\n"
                            + "                                    //,\n"
                            + "                                    //\"sScrollY\": \"200px\",\n"
                            + "                                    //\"bPaginate\": false,\n"
                            + "\n"
                            + "                                    //\"sScrollX\": \"100%\",\n"
                            + "                                    //\"sScrollXInner\": \"120%\",\n"
                            + "                                    //\"bScrollCollapse\": true,\n"
                            + "                                    //Note: if you are applying horizontal scrolling (sScrollX) on a \".table-bordered\"\n"
                            + "                                    //you may want to wrap the table inside a \"div.dataTables_borderWrap\" element\n"
                            + "\n"
                            + "                                    //\"iDisplayLength\": 50\n"
                            + "\n"
                            + "\n"
                            + "                                    select: {\n"
                            + "                                        style: 'multi'\n"
                            + "                                    }\n"
                            + "                                });\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                        $.fn.dataTable.Buttons.defaults.dom.container.className = 'dt-buttons btn-overlap btn-group btn-overlap';\n"
                            + "\n"
                            + "                        new $.fn.dataTable.Buttons(myTable, {\n"
                            + "                            buttons: [\n"
                            + "                                {\n"
                            + "                                    \"extend\": \"colvis\",\n"
                            + "                                    \"text\": \"<i class='fa fa-search bigger-110 blue'></i> <span class='hidden'>Show/hide columns</span>\",\n"
                            + "                                    \"className\": \"btn btn-white btn-primary btn-bold\",\n"
                            + "                                    columns: ':not(:first):not(:last)'\n"
                            + "                                },\n"
                            + "                                {\n"
                            + "                                    \"extend\": \"copy\",\n"
                            + "                                    \"text\": \"<i class='fa fa-copy bigger-110 pink'></i> <span class='hidden'>Copy to clipboard</span>\",\n"
                            + "                                    \"className\": \"btn btn-white btn-primary btn-bold\"\n"
                            + "                                },\n"
                            + "                                {\n"
                            + "                                    \"extend\": \"csv\",\n"
                            + "                                    \"text\": \"<i class='fa fa-database bigger-110 orange'></i> <span class='hidden'>Export to CSV</span>\",\n"
                            + "                                    \"className\": \"btn btn-white btn-primary btn-bold\"\n"
                            + "                                },\n"
                            + "                                {\n"
                            + "                                    \"extend\": \"excel\",\n"
                            + "                                    \"text\": \"<i class='fa fa-file-excel-o bigger-110 green'></i> <span class='hidden'>Export to Excel</span>\",\n"
                            + "                                    \"className\": \"btn btn-white btn-primary btn-bold\"\n"
                            + "                                },\n"
                            + "                                {\n"
                            + "                                    \"extend\": \"pdf\",\n"
                            + "                                    \"text\": \"<i class='fa fa-file-pdf-o bigger-110 red'></i> <span class='hidden'>Export to PDF</span>\",\n"
                            + "                                    \"className\": \"btn btn-white btn-primary btn-bold\"\n"
                            + "                                },\n"
                            + "                                {\n"
                            + "                                    \"extend\": \"print\",\n"
                            + "                                    \"text\": \"<i class='fa fa-print bigger-110 grey'></i> <span class='hidden'>Print</span>\",\n"
                            + "                                    \"className\": \"btn btn-white btn-primary btn-bold\",\n"
                            + "                                    autoPrint: false,\n"
                            + "                                    message: 'RECENT TRANSACTION REPORT'\n"
                            + "                                }\n"
                            + "                            ]\n"
                            + "                        });\n"
                            + "                        myTable.buttons().container().appendTo($('.tableTools-container'));\n"
                            + "\n"
                            + "                        //style the message box\n"
                            + "                        var defaultCopyAction = myTable.button(1).action();\n"
                            + "                        myTable.button(1).action(function (e, dt, button, config) {\n"
                            + "                            defaultCopyAction(e, dt, button, config);\n"
                            + "                            $('.dt-button-info').addClass('gritter-item-wrapper gritter-info gritter-center white');\n"
                            + "                        });\n"
                            + "\n"
                            + "\n"
                            + "                        var defaultColvisAction = myTable.button(0).action();\n"
                            + "                        myTable.button(0).action(function (e, dt, button, config) {\n"
                            + "\n"
                            + "                            defaultColvisAction(e, dt, button, config);\n"
                            + "\n"
                            + "\n"
                            + "                            if ($('.dt-button-collection > .dropdown-menu').length == 0) {\n"
                            + "                                $('.dt-button-collection')\n"
                            + "                                        .wrapInner('<ul class=\"dropdown-menu dropdown-light dropdown-caret dropdown-caret\" />')\n"
                            + "                                        .find('a').attr('href', '#').wrap(\"<li />\")\n"
                            + "                            }\n"
                            + "                            $('.dt-button-collection').appendTo('.tableTools-container .dt-buttons')\n"
                            + "                        });\n"
                            + "\n"
                            + "                        ////\n"
                            + "\n"
                            + "                        setTimeout(function () {\n"
                            + "                            $($('.tableTools-container')).find('a.dt-button').each(function () {\n"
                            + "                                var div = $(this).find(' > div').first();\n"
                            + "                                if (div.length == 1)\n"
                            + "                                    div.tooltip({container: 'body', title: div.parent().text()});\n"
                            + "                                else\n"
                            + "                                    $(this).tooltip({container: 'body', title: $(this).text()});\n"
                            + "                            });\n"
                            + "                        }, 500);\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                        myTable.on('select', function (e, dt, type, index) {\n"
                            + "                            if (type === 'row') {\n"
                            + "                                $(myTable.row(index).node()).find('input:checkbox').prop('checked', true);\n"
                            + "                            }\n"
                            + "                        });\n"
                            + "                        myTable.on('deselect', function (e, dt, type, index) {\n"
                            + "                            if (type === 'row') {\n"
                            + "                                $(myTable.row(index).node()).find('input:checkbox').prop('checked', false);\n"
                            + "                            }\n"
                            + "                        });\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                        /////////////////////////////////\n"
                            + "                        //table checkboxes\n"
                            + "                        $('th input[type=checkbox], td input[type=checkbox]').prop('checked', false);\n"
                            + "\n"
                            + "                        //select/deselect all rows according to table header checkbox\n"
                            + "                        $('#dynamic-table > thead > tr > th input[type=checkbox], #dynamic-table_wrapper input[type=checkbox]').eq(0).on('click', function () {\n"
                            + "                            var th_checked = this.checked;//checkbox inside \"TH\" table header\n"
                            + "\n"
                            + "                            $('#dynamic-table').find('tbody > tr').each(function () {\n"
                            + "                                var row = this;\n"
                            + "                                if (th_checked)\n"
                            + "                                    myTable.row(row).select();\n"
                            + "                                else\n"
                            + "                                    myTable.row(row).deselect();\n"
                            + "                            });\n"
                            + "                        });\n"
                            + "\n"
                            + "                        //select/deselect a row when the checkbox is checked/unchecked\n"
                            + "                        $('#dynamic-table').on('click', 'td input[type=checkbox]', function () {\n"
                            + "                            var row = $(this).closest('tr').get(0);\n"
                            + "                            if (this.checked)\n"
                            + "                                myTable.row(row).deselect();\n"
                            + "                            else\n"
                            + "                                myTable.row(row).select();\n"
                            + "                        });\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                        $(document).on('click', '#dynamic-table .dropdown-toggle', function (e) {\n"
                            + "                            e.stopImmediatePropagation();\n"
                            + "                            e.stopPropagation();\n"
                            + "                            e.preventDefault();\n"
                            + "                        });\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                        //And for the first simple table, which doesn't have TableTools or dataTables\n"
                            + "                        //select/deselect all rows according to table header checkbox\n"
                            + "                        var active_class = 'active';\n"
                            + "                        $('#simple-table > thead > tr > th input[type=checkbox]').eq(0).on('click', function () {\n"
                            + "                            var th_checked = this.checked;//checkbox inside \"TH\" table header\n"
                            + "\n"
                            + "                            $(this).closest('table').find('tbody > tr').each(function () {\n"
                            + "                                var row = this;\n"
                            + "                                if (th_checked)\n"
                            + "                                    $(row).addClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', true);\n"
                            + "                                else\n"
                            + "                                    $(row).removeClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', false);\n"
                            + "                            });\n"
                            + "                        });\n"
                            + "\n"
                            + "                        //select/deselect a row when the checkbox is checked/unchecked\n"
                            + "                        $('#simple-table').on('click', 'td input[type=checkbox]', function () {\n"
                            + "                            var $row = $(this).closest('tr');\n"
                            + "                            if ($row.is('.detail-row '))\n"
                            + "                                return;\n"
                            + "                            if (this.checked)\n"
                            + "                                $row.addClass(active_class);\n"
                            + "                            else\n"
                            + "                                $row.removeClass(active_class);\n"
                            + "                        });\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                        /********************************/\n"
                            + "                        //add tooltip for small view action buttons in dropdown menu\n"
                            + "                        $('[data-rel=\"tooltip\"]').tooltip({placement: tooltip_placement});\n"
                            + "\n"
                            + "                        //tooltip placement on right or left\n"
                            + "                        function tooltip_placement(context, source) {\n"
                            + "                            var $source = $(source);\n"
                            + "                            var $parent = $source.closest('table')\n"
                            + "                            var off1 = $parent.offset();\n"
                            + "                            var w1 = $parent.width();\n"
                            + "\n"
                            + "                            var off2 = $source.offset();\n"
                            + "                            //var w2 = $source.width();\n"
                            + "\n"
                            + "                            if (parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2))\n"
                            + "                                return 'right';\n"
                            + "                            return 'left';\n"
                            + "                        }\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                        /***************/\n"
                            + "                        $('.show-details-btn').on('click', function (e) {\n"
                            + "                            e.preventDefault();\n"
                            + "                            $(this).closest('tr').next().toggleClass('open');\n"
                            + "                            $(this).find(ace.vars['.icon']).toggleClass('fa-angle-double-down').toggleClass('fa-angle-double-up');\n"
                            + "                        });\n"
                            + "                        /***************/\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "\n"
                            + "                        /**\n"
                            + "                         //add horizontal scrollbars to a simple table\n"
                            + "                         $('#simple-table').css({'width':'2000px', 'max-width': 'none'}).wrap('<div style=\"width: 1000px;\" />').parent().ace_scroll(\n"
                            + "                         {\n"
                            + "                         horizontal: true,\n"
                            + "                         styleClass: 'scroll-top scroll-dark scroll-visible',//show the scrollbars on top(default is bottom)\n"
                            + "                         size: 2000,\n"
                            + "                         mouseWheelLock: true\n"
                            + "                         }\n"
                            + "                         ).css('padding-top', '12px');\n"
                            + "                         */\n"
                            + "\n"
                            + "\n"
                            + "                    })\n"
                            + "        </script>\n"
                            + "    </body>\n"
                            + "</html>\n";

                } else {

                    response.sendRedirect("LOGIN.jsp");
                }
            }

        }

    }
}
